python/src/app/views/util/record.py: ()を付ける記録が間違っていた問題を修正
speedcubing-japan/scj pull request #1
Opened 2021-08-07 16:34 UTC by ky12228121

### 修正事項

 - ()を付ける記録が間違っていた問題を修正
 - tests/*をignoreに追加

2021-08-07 18:35 UTC, speedcubing-japan requested changes
僕のコードなので恐縮なんですが、

1. convert内でminutes_convertをcallしているのでconvertにまとめてしまおう。
2. -1, -2, DNF, DNSをメンバに定数で定義してそれを参照する形にしましょう。(リテラルはベタガキしない)

上記直していただいたら再度Reviewします。
おそらく上記を治すともう少し判定が短くなる気配がします。直感ですが…。

2021-08-07 18:41 UTC, speedsolve reviewed
次からこちらのアカウントからReviewします

2021-08-08 07:21 UTC, ky12228121 commented
### 修正#2
- DNF、DNS、-1、-2を定数として定義
- minutes_convertをconvertに統一
- (おまけ) 分岐にコメント追加
- (おまけ) ()をつける関数を作成(add_brackets)

2021-08-08 14:18 UTC, speedsolve commented
問題ないので取り込みます。

2021-08-08 14:19 UTC, merged